apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# CI replaces this bootstrap marker with the immutable digest it has just built.
images:
- digest: sha256:0192a5c9aab6ffe452983413281ffa5da97723a9984d05bd6b067919c96ffddb
  name: ghcr.io/dohr-michael/temper-modules
