apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# CI replaces this bootstrap marker with the immutable digest it has just built.
images:
- digest: sha256:bded767fef5482b410a4b2998ef873d7ba42d3bbb023dcb1013fbd6a3119d0db
  name: ghcr.io/dohr-michael/temper-modules
